export const CATEG_FETCH = 'CATEG_FETCH';


export const PROD_FETCH = 'PROD_FETCH';
export const PROD_FETCH_SUCCES = 'PROD_FETCH_SUCCES';
export const PROD_FETCH_START = 'PROD_FETCH_START';
export const PROD_FETCH_ERROR = 'PROD_FETCH_ERROR';
export const PROD_UPDATE = 'PROD_UPDATE';
export const PROD_DELETE = 'PROD_DELETE';
export const PROD_INSERT = 'PROD_INSERT';
export const PROD_GET_UNO_START = 'PROD_GET_UNO_START';
export const PROD_GET_UNO_SUCCES = 'PROD_GET_UNO_SUCCES';
export const PROD_GET_UNO_ERROR = 'PROD_GET_UNO_ERROR';
export const PROD_GET_UNO_CLEAR = 'PROD_GET_UNO_CLEAR';
export const PROD_GET_UPDATE_START = 'PROD_GET_UPDATE_START';
export const PROD_GET_INSERT_START = 'PROD_GET_INSERT_START';
export const PROD_GET_MODIFY_START = 'PROD_GET_MODIFY_START';
export const PROD_GET_MODIFY_SUCCES = 'PROD_GET_MODIFY_SUCCES';
export const PROD_GET_MODIFY_ERROR = 'PROD_GET_MODIFY_ERROR';
export const PROD_GET_DELETE_START = 'PROD_GET_DELETE_START';